#!/bin/bash

# Args:
#  1: subtype (H or N)
#  2: path to directory containing fasta files of sequences against which to calculate
#     coverage (e.g., if subtype is H, this directory should contain the files
#     2k8_[SUBTYPE]Nstar.fasta where [SUBTYPE] is H1, H2, etc.)
#  3: path to tmp directory
#  4: path to output directory
#
# This uses the output in tmp/ generated by calculate_subtype_coverage.sh

H_SUBTYPES=( "H1" "H2" "H3" "H4" "H5" "H6" "H7" "H8" "H9" "H10" "H11" "H12" "H13" "H14" "H15" "H16" )
N_SUBTYPES=( "N1" "N2" "N3" "N4" "N5" "N6" "N7" "N8" "N9" )
if [[ $1 == "H" ]]; then
    SUBTYPES=("${H_SUBTYPES[@]}")
elif [[ $1 == "N" ]]; then
    SUBTYPES=("${N_SUBTYPES[@]}")
else
    echo "Unknown subtype $1"
    exit 1
fi

seqsdir=$2
tmpdir=$3
outdir=$4

for subtype in "${SUBTYPES[@]}"; do
    if [[ $1 == "H" ]]; then
        seqs="$seqsdir/2k8_${subtype}Nstar.fasta"
    elif [[ $1 == "N" ]]; then
        seqs="$seqsdir/2k8_Hstar${subtype}.fasta"
    else
        echo "Unknown subtype $1"
        exit 1
    fi

    # Take year to match the regular expression '/[year] ' where [year] is
    # 4 digits
    grep '>' $seqs | grep -Po '/\d{4} ' | sed 's/\///' > $tmpdir/${subtype}.year.txt

    # Paste accessions with year
    grep '>' $seqs | awk '{print $1}' | sed 's/>//' > $tmpdir/${subtype}.acc.txt
    paste $tmpdir/${subtype}.acc.txt $tmpdir/${subtype}.year.txt > $tmpdir/${subtype}.acc-and-year.txt

    # Go through each unique year
    echo -e "year\tnum.seqs\tnum.covered\tfrac.covered" > $outdir/covg-by-year.as27.${subtype}.tsv
    while read year; do
        # Find all accessions from year
        cat $tmpdir/${subtype}.acc-and-year.txt | awk -v y="$year" '$2==y {print $1}' | sort > $tmpdir/${subtype}.${year}.acc.txt

        # Pull out alignments with score AS >= 27
        cat $tmpdir/guides-to-${subtype}.sam | awk '{split($14, subfield, ":"); if(subfield[3]>=27) print $0}' > $tmpdir/guides-to-${subtype}.as27.sam

        numseqs=$(wc -l $tmpdir/${subtype}.${year}.acc.txt | awk '{print $1}')
        numcovered=$(comm -12 $tmpdir/${subtype}.${year}.acc.txt <(cat $tmpdir/guides-to-${subtype}.as27.sam | awk '{print $3}' | sort) | wc -l)
        frac=$(echo "scale=4; $numcovered/$numseqs" | bc)

        echo -e "$year\t$numseqs\t$numcovered\t$frac" >> $outdir/covg-by-year.as27.${subtype}.tsv
        rm $tmpdir/${subtype}.${year}.acc.txt
    done < <(cat $tmpdir/${subtype}.acc-and-year.txt | awk '{print $2}' | sed '/^$/d' | sort -n | uniq)

    rm $tmpdir/guides-to-${subtype}.as27.sam
    rm $tmpdir/${subtype}.year.txt
    rm $tmpdir/${subtype}.acc.txt
done
